# Generated by Django 4.2.19 on 2025-05-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_alter_bill_code_ext_alter_bill_code_tp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='code',
            field=models.CharField(db_column='Code', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='code',
            field=models.CharField(db_column='Code', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalbill',
            name='code',
            field=models.CharField(db_column='Code', db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalbillitem',
            name='code',
            field=models.CharField(db_column='Code', db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='code',
            field=models.CharField(db_column='Code', db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalinvoicelineitem',
            name='code',
            field=models.CharField(db_column='Code', db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='code',
            field=models.CharField(db_column='Code', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='code',
            field=models.CharField(db_column='Code', max_length=255, unique=True),
        ),
    ]
