# Generated by Django 4.2.19 on 2025-05-05 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_alter_bill_code_alter_billitem_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='cron_job_code',
            field=models.CharField(db_column='CronJobCode', db_index=True, default=uuid.uuid4, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalinvoicelineitem',
            name='cronjobcode',
            field=models.CharField(db_column='CronJobCode', db_index=True, default=uuid.uuid4, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cron_job_code',
            field=models.CharField(db_column='CronJobCode', default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='cronjobcode',
            field=models.CharField(db_column='CronJobCode', default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
